<a href="https://colab.research.google.com/github/Sanathcharan/Data-Science-ExcelR/blob/main/DBscan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv('shopping_data.csv')
df

     CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
..          ...     ...  ...                 ...                     ...
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Genre                   200 non-null    object
 2   Age                     200 non-null    int64
 3   Annual Income (k$)      200 non-null    int64
 4   Spending Score (1-100)  200 non-null    int64
dtypes: int64(4), object(1)
memory usage: 7.9+ KB

In [ ]:
df.head()

   CustomerID   Genre  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [ ]:
df.isnull().sum()

CustomerID                0
Genre                     0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.shape

(200, 5)

In [ ]:
df.size

1000

In [ ]:
df.drop(['CustomerID','Genre'],axis=1,inplace=True)

In [ ]:
df.columns

Index(['Age', 'Annual Income (k$)', 'Spending Score (1-100)'], dtype='object')

In [ ]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
df[['Age','Annual Income (k$)','Spending Score (1-100)']]=sc.fit_transform(df[['Age','Annual Income (k$)','Spending Score (1-100)']])

In [ ]:
from sklearn.cluster import DBSCAN
DBSCAN()
dbscan=DBSCAN(eps=0.75,min_samples=4)
dbscan.fit(df)

DBSCAN(eps=0.75, min_samples=4)

In [ ]:
dbscan.labels_

array([-1,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,
        0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0, -1,  0, -1,  0, -1, -1])

In [ ]:
cl=pd.DataFrame(dbscan.labels_,columns=['cluster'])
cl
print(cl['cluster'].value_counts())

cluster
 0    192
-1      8
Name: count, dtype: int64

In [ ]:
clustered=pd.concat([df,cl],axis=1)

In [ ]:
noisedata=clustered[clustered['cluster']==-1]
print(noisedata)

          Age  Annual Income (k$)  Spending Score (1-100)  cluster
0   -1.424569           -1.738999               -0.434801       -1
2   -1.352802           -1.700830               -1.715913       -1
11  -0.276302           -1.586321                1.894492       -1
19  -0.276302           -1.433644                1.855671       -1
194  0.584899            2.268791               -1.327697       -1
196  0.441365            2.497807               -0.861839       -1
198 -0.491602            2.917671               -1.250054       -1
199 -0.635135            2.917671                1.273347       -1

In [ ]:
clustered[clustered['cluster']==-1]

          Age  Annual Income (k$)  Spending Score (1-100)  cluster
0   -1.424569           -1.738999               -0.434801       -1
2   -1.352802           -1.700830               -1.715913       -1
11  -0.276302           -1.586321                1.894492       -1
19  -0.276302           -1.433644                1.855671       -1
194  0.584899            2.268791               -1.327697       -1
196  0.441365            2.497807               -0.861839       -1
198 -0.491602            2.917671               -1.250054       -1
199 -0.635135            2.917671                1.273347       -1

In [ ]:
from sklearn.metrics import silhouette_score

# Calculate and print the silhouette score
print("Silhouette Score:", silhouette_score(df, dbscan.labels_))

Silhouette Score: 0.2716676971651858

In [ ]:
df

          Age  Annual Income (k$)  Spending Score (1-100)
0   -1.424569           -1.738999               -0.434801
1   -1.281035           -1.738999                1.195704
2   -1.352802           -1.700830               -1.715913
3   -1.137502           -1.700830                1.040418
4   -0.563369           -1.662660               -0.395980
..        ...                 ...                     ...
195 -0.276302            2.268791                1.118061
196  0.441365            2.497807               -0.861839
197 -0.491602            2.497807                0.923953
198 -0.491602            2.917671               -1.250054
199 -0.635135            2.917671                1.273347

[200 rows x 3 columns]

In [ ]:
len({-1,0})

2

In [ ]:
from sklearn.cluster import DBSCAN
from sklearn.metrics import silhouette_score

for eps in [0.2, 0.4, 0.6, 0.8, 1.0]:
    db = DBSCAN(eps=eps, min_samples=4)
    labels = db.fit_predict(df)

    # Number of clusters (excluding noise)
    if -1 in labels:
     subtract = 1
    else:
     subtract = 0

    n_clusters = len(set(labels)) - subtract

    # Calculate Silhouette Score
    if n_clusters > 1:
        score = silhouette_score(df, labels)
    else:
        score = "Not Applicable"

    print(f"eps = {eps}")
    print("Clusters:", n_clusters)
    #print("Noise:", n_noise)
    print("Silhouette Score:", score)
    print("-" * 40)

eps = 0.2
Clusters: 3
Silhouette Score: -0.3399135394830671
----------------------------------------
eps = 0.4
Clusters: 8
Silhouette Score: 0.11311020759466783
----------------------------------------
eps = 0.6
Clusters: 3
Silhouette Score: 0.15527415663221333
----------------------------------------
eps = 0.8
Clusters: 1
Silhouette Score: Not Applicable
----------------------------------------
eps = 1.0
Clusters: 1
Silhouette Score: Not Applicable
----------------------------------------